login: &login
  adapter: mysql
  username: root
  database: taylorinc
  
development:
  <<: *login
  socket: /tmp/mysql.sock
  password: 

test:
  <<: *login
  socket: /tmp/mysql.sock
  password: 

production:
  <<: *login
  socket: /var/run/mysqld/mysqld.sock
  password: 
