development:
  bucket: taylorinc_dev
  access_key_id: 12XJVY7EK35EKWDSAX82
  secret_access_key: 6EsxNRpDWxpO3Yr8G/J7f3xdo6YtFTVGYtHj/fNl

test:
  bucket: taylorinc_staging
  access_key_id: 12XJVY7EK35EKWDSAX82
  secret_access_key: 6EsxNRpDWxpO3Yr8G/J7f3xdo6YtFTVGYtHj/fNl

production:
  bucket: taylorinc
  access_key_id: 12XJVY7EK35EKWDSAX82
  secret_access_key: 6EsxNRpDWxpO3Yr8G/J7f3xdo6YtFTVGYtHj/fNl
